### ISSUE TITLE
Planning Feedback

### ISSUE THREAD

**Issue by sa-battle** [ArafatRChowdhury/Jobcator#1]
Use markdown to make “Jobcator” a top level heading in your readme.md.
Please include a link to the dataset in Bristol Open Data.

Planning.md
Remove TODOs once done.
If you include a numbered list bin a section, always provide a line of introduction.Some points may need further explanation. There should be a license associated with all the Open Data, but you haven’t indicated which dataset you’re using. You haven’t included a context diagram, nor indeed the images folder.

Mark range: NEEDS WORK

**Comment by ArafatRChowdhury** [comment]
Resolved as of November 6th 2023
