### ISSUE TITLE
Implementation feedback

### ISSUE THREAD

**Issue by sa-battle** [ArafatRChowdhury/Jobcator#4]
The project structure should also include other folders such as the docs folder.
Please mention what kinds of diagram you're using (ie. UML component diagram, and UML object diagram)
You could also add which pages use this JSON object structure.
Don't forget to lint the code.

MARK RANGE: MERIT

**Comment by ArafatRChowdhury** [comment]
Docs folder structure added, diagrams used mentioned, code linted as of April 29th 2024
